### ISSUE TITLE
Env branch with '-' can't be deployed

### ISSUE THREAD

**Issue by keiranmraine** [SciTools/conda-gitenv#38]
I suspect this is due to matching against the tag names.

For example an environment of `casm-perl` will resolve and tag, but not deploy.  No warnings are emitted.  Renaming it to `casmPerl` handles the problem.

Suggest having `gitenv resolve` throw an error when a hyphenated branch is detected.

**Comment by pelson** [comment]
This is something I'd love to address. I would actually like to allow environments with a dash, but agree, your solution does move us forwards.
