### ISSUE TITLE
Work on CLI interface

### ISSUE THREAD

**Issue by pelson** [SciTools/conda-gitenv#5]
n.b. currently:

```
conda-env-tracker <repo>
conda-env-tracker-timestamp <repo>
conda-env-tracker-labeltag <repo>
conda-env-tracker-deploy <repo> <destination>
```

It would also be nice to come up with a suitable name which covers all of this functionality (i.e. the "conda environments in a git repo" bit).

**Comment by rhattersley** [comment]
Perhaps a sub-command model?

```
conda-env-tracker ??? <repo>
conda-env-tracker timestamp <repo>
conda-env-tracker labeltag <repo>
conda-env-tracker deploy <repo> <destination>
```

**Comment by pelson** [comment]
> Perhaps a sub-command model?

I think that is sensible. Still not sure about the prefix though (the `conda-env-tracker` part).

```
conda-env-tracker ??? <repo> ---> conda-env-tracker manifesticate <repo>
```

:wink:

**Comment by rhattersley** [comment]
:+1: for `manifesticate` :grin:

**Comment by pelson** [comment]
> Still not sure about the prefix though (the conda-env-tracker part)

How about `conda gitenv`?

```
conda gitenv resolve <repo>  (alias: manifesticate)
conda gitenv autotag <repo> [--branch=branch_to_tag]
conda gitenv label <repo> <label> <tag_to_label> [--progress-next]
conda gitenv deploy <repo> <destination>
```

Still unsure about how to go about the auto-label-progression thing. It is a little bit special to automatically move `next -> current -> previous -> <delete>`, but is certainly not a thing I want to leave to individual user error. Proof of the pudding will come in the next few days, maybe that will help inform the workflow.

**Comment by rhattersley** [comment]
`gitenv` is OK. It's easy/quick enough to type, so :+1: for using it for now.
